name: Android CI

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*' # وقتی تگ ورژن جدید مثلا v1.2 پوش بشه، اجرا میشه
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # دسترسی لازم برای ساخت Release در گیت‌هاب

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Create local.properties and .env
      run: |
        touch local.properties
        touch .env

    - name: Generate debug keystore
      run: keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
        
    - name: Build Debug APK with Gradle
      run: gradle assembleDebug

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk storeflow-update.apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: storeflow-update.apk

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v') # فقط وقتی تگ ورژن زده بشه این مرحله اجرا میشه
      uses: softprops/action-gh-release@v2
      with:
        files: storeflow-update.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

